const chineseWords = [
    { chinese: "你好", pinyin: "nǐ hǎo", english: "Hello" },
    { chinese: "谢谢", pinyin: "xiè xiè", english: "Thank you" },
    { chinese: "再见", pinyin: "zài jiàn", english: "Goodbye" },
    { chinese: "不客气", pinyin: "bú kè qì", english: "You're welcome" },
    { chinese: "对不起", pinyin: "duì bu qǐ", english: "Sorry" },
    { chinese: "没关系", pinyin: "méi guān xi", english: "It's okay" },
    { chinese: "请问", pinyin: "qǐng wèn", english: "Excuse me" },
    { chinese: "好的", pinyin: "hǎo de", english: "Okay" },
    { chinese: "是", pinyin: "shì", english: "Yes" },
    { chinese: "不是", pinyin: "bú shì", english: "No" },
    { chinese: "有", pinyin: "yǒu", english: "Have" },
    { chinese: "没有", pinyin: "méi yǒu", english: "Don't have" },
    { chinese: "我", pinyin: "wǒ", english: "I" },
    { chinese: "你", pinyin: "nǐ", english: "You" },
    { chinese: "他", pinyin: "tā", english: "He" },
    { chinese: "她", pinyin: "tā", english: "She" },
    { chinese: "我们", pinyin: "wǒ men", english: "We" },
    { chinese: "你们", pinyin: "nǐ men", english: "You (plural)" },
    { chinese: "他们", pinyin: "tā men", english: "They" },
    { chinese: "这", pinyin: "zhè", english: "This" },
    { chinese: "那", pinyin: "nà", english: "That" },
    { chinese: "这里", pinyin: "zhè lǐ", english: "Here" },
    { chinese: "那里", pinyin: "nà lǐ", english: "There" },
    { chinese: "什么", pinyin: "shén me", english: "What" },
    { chinese: "谁", pinyin: "shuí", english: "Who" },
    { chinese: "哪儿", pinyin: "nǎr", english: "Where" },
    { chinese: "为什么", pinyin: "wèi shén me", english: "Why" },
    { chinese: "怎么样", pinyin: "zěn me yàng", english: "How" },
    { chinese: "多少", pinyin: "duō shao", english: "How much/many" },
    { chinese: "现在", pinyin: "xiàn zài", english: "Now" },
    { chinese: "今天", pinyin: "jīn tiān", english: "Today" },
    { chinese: "明天", pinyin: "míng tiān", english: "Tomorrow" },
    { chinese: "昨天", pinyin: "zuó tiān", english: "Yesterday" },
    { chinese: "早上", pinyin: "zǎo shang", english: "Morning" },
    { chinese: "中午", pinyin: "zhōng wǔ", english: "Noon" },
    { chinese: "下午", pinyin: "xià wǔ", english: "Afternoon" },
    { chinese: "晚上", pinyin: "wǎn shang", english: "Evening" },
    { chinese: "一点", pinyin: "yī diǎn", english: "1 o'clock" },
    { chinese: "两点", pinyin: "liǎng diǎn", english: "2 o'clock" },
    { chinese: "三点", pinyin: "sān diǎn", english: "3 o'clock" },
    // ... add more numbers as needed
    { chinese: "吃饭", pinyin: "chī fàn", english: "To eat (a meal)" },
    { chinese: "喝水", pinyin: "hē shuǐ", english: "To drink water" },
    { chinese: "睡觉", pinyin: "shuì jiào", english: "To sleep" },
    { chinese: "去", pinyin: "qù", english: "To go" },
    { chinese: "来", pinyin: "lái", english: "To come" },
    { chinese: "看", pinyin: "kàn", english: "To see/watch" },
    { chinese: "听", pinyin: "tīng", english: "To listen" },
    { chinese: "说", pinyin: "shuō", english: "To speak" },
    { chinese: "读", pinyin: "dú", english: "To read" },
    { chinese: "写", pinyin: "xiě", english: "To write" },
    { chinese: "做", pinyin: "zuò", english: "To do" },
    { chinese: "学习", pinyin: "xué xí", english: "To study" },
    { chinese: "工作", pinyin: "gōng zuò", english: "To work" },
    { chinese: "玩", pinyin: "wán", english: "To play" },
    { chinese: "买", pinyin: "mǎi", english: "To buy" },
    { chinese: "卖", pinyin: "mài", english: "To sell" },
    { chinese: "喜欢", pinyin: "xǐ huan", english: "To like" },
    { chinese: "爱", pinyin: "ài", english: "To love" },
    { chinese: "想", pinyin: "xiǎng", english: "To want/miss" },
    { chinese: "知道", pinyin: "zhī dào", english: "To know" },
    { chinese: "可以", pinyin: "kě yǐ", english: "Can/May" },
    { chinese: "会", pinyin: "huì", english: "To be able to" },
    { chinese: "要", pinyin: "yào", english: "To want/need" },
    { chinese: "应该", pinyin: "yīng gāi", english: "Should" },
    { chinese: "很", pinyin: "hěn", english: "Very" },
    { chinese: "太", pinyin: "tài", english: "Too" },
    { chinese: "也", pinyin: "yě", english: "Also" },
    { chinese: "都", pinyin: "dōu", english: "All/Both" },
    { chinese: "和", pinyin: "hé", english: "And" },
    { chinese: "但是", pinyin: "dàn shì", english: "But" },
    { chinese: "因为", pinyin: "yīn wèi", english: "Because" },
    { chinese: "所以", pinyin: "suǒ yǐ", english: "So" },
    { chinese: "如果", pinyin: "rú guǒ", english: "If" },
    { chinese: "名字", pinyin: "míng zi", english: "Name" },
    { chinese: "人", pinyin: "rén", english: "Person" },
    { chinese: "家", pinyin: "jiā", english: "Home/Family" },
    { chinese: "朋友", pinyin: "péng you", english: "Friend" },
    { chinese: "先生", pinyin: "xiān sheng", english: "Mr." },
    { chinese: "小姐", pinyin: "xiǎo jie", english: "Miss" },
    { chinese: "老师", pinyin: "lǎo shī", english: "Teacher" },
    { chinese: "学生", pinyin: "xué sheng", english: "Student" },
    { chinese: "东西", pinyin: "dōng xi", english: "Thing" },
    { chinese: "钱", pinyin: "qián", english: "Money" },
    { chinese: "时间", pinyin: "shí jiān", english: "Time" },
    { chinese: "年", pinyin: "nián", english: "Year" },
    { chinese: "天", pinyin: "tiān", english: "Day" },
    { chinese: "手机", pinyin: "shǒu jī", english: "Mobile phone" },
    { chinese: "电脑", pinyin: "diàn nǎo", english: "Computer" },
    { chinese: "车", pinyin: "chē", english: "Car" },
    { chinese: "房子", pinyin: "fáng zi", english: "House" },
    { chinese: "门", pinyin: "mén", english: "Door" },
    { chinese: "水", pinyin: "shuǐ", english: "Water" },
    { chinese: "饭", pinyin: "fàn", english: "Rice/Meal" },
    { chinese: "菜", pinyin: "cài", english: "Dish/Vegetable" },
    { chinese: "水果", pinyin: "shuǐ guǒ", english: "Fruit" },
    { chinese: "颜色", pinyin: "yán sè", english: "Color" },
    { chinese: "红色", pinyin: "hóng sè", english: "Red" },
    { chinese: "黄色", pinyin: "huáng sè", english: "Yellow" },
    { chinese: "蓝色", pinyin: "lán sè", english: "Blue" },
    // ... add more colors
    { chinese: "中国", pinyin: "zhōng guó", english: "China" },
    { chinese: "北京", pinyin: "běi jīng", english: "Beijing" },
    { chinese: "怎么样", pinyin: "zěnmeyàng", english: "How about...? / How is...?" },
{ chinese: "一点儿", pinyin: "yīdiǎnr", english: "A little" },
{ chinese: "没有", pinyin: "méiyǒu", english: "Not have / There isn't" },
{ chinese: "可能", pinyin: "kěnéng", english: "Maybe / Possible" },
{ chinese: "应该", pinyin: "yīnggāi", english: "Should" },
{ chinese: "觉得", pinyin: "juéde", english: "To feel / To think" },
{ chinese: "知道", pinyin: "zhīdào", english: "To know" },
{ chinese: "了解", pinyin: "liǎojiě", english: "To understand" },
{ chinese: "问题", pinyin: "wèntí", english: "Question / Problem" },
{ chinese: "意思", pinyin: "yìsi", english: "Meaning" },
{ chinese: "时候", pinyin: "shíhou", english: "Time" },
{ chinese: "分钟", pinyin: "fēnzhōng", english: "Minute" },
{ chinese: "小时", pinyin: "xiǎoshí", english: "Hour" },
{ chinese: "星期", pinyin: "xīngqī", english: "Week" },
{ chinese: "月", pinyin: "yuè", english: "Month" },
{ chinese: "年", pinyin: "nián", english: "Year" },
{ chinese: "今天", pinyin: "jīntiān", english: "Today" },
{ chinese: "明天", pinyin: "míngtiān", english: "Tomorrow" },
{ chinese: "昨天", pinyin: "zuótiān", english: "Yesterday" },
{ chinese: "最近", pinyin: "zuìjìn", english: "Recently" },
{ chinese: "先生", pinyin: "xiānsheng", english: "Mr." },
{ chinese: "小姐", pinyin: "xiǎojie", english: "Miss" },
{ chinese: "女士", pinyin: "nǚshì", english: "Ms. / Mrs." },
{ chinese: "朋友", pinyin: "péngyou", english: "Friend" },
{ chinese: "家人", pinyin: "jiārén", english: "Family member" },
{ chinese: "同学", pinyin: "tóngxué", english: "Classmate" },
{ chinese: "同事", pinyin: "tóngshì", english: "Colleague" },
{ chinese: "医生", pinyin: "yīshēng", english: "Doctor" },
{ chinese: "老师", pinyin: "lǎoshī", english: "Teacher" },
{ chinese: "学生", pinyin: "xuésheng", english: "Student" },
{ chinese: "地方", pinyin: "dìfang", english: "Place" },
{ chinese: "国家", pinyin: "guójiā", english: "Country" },
{ chinese: "城市", pinyin: "chéngshì", english: "City" },
{ chinese: "学校", pinyin: "xuéxiào", english: "School" },
{ chinese: "医院", pinyin: "yīyuàn", english: "Hospital" },
{ chinese: "公司", pinyin: "gōngsī", english: "Company" },
{ chinese: "商店", pinyin: "shāngdiàn", english: "Shop / Store" },
{ chinese: "饭店", pinyin: "fàndiàn", english: "Restaurant" },
{ chinese: "酒店", pinyin: "jiǔdiàn", english: "Hotel" },
{ chinese: "机场", pinyin: "jīchǎng", english: "Airport" },
{ chinese: "想", pinyin: "xiǎng", english: "To want / To think" },
{ chinese: "需要", pinyin: "xūyào", english: "To need" },
{ chinese: "喜欢", pinyin: "xǐhuan", english: "To like" },
{ chinese: "爱", pinyin: "ài", english: "To love" },
{ chinese: "吃", pinyin: "chī", english: "To eat" },
{ chinese: "喝", pinyin: "hē", english: "To drink" },
{ chinese: "睡觉", pinyin: "shuìjiào", english: "To sleep" },
{ chinese: "走路", pinyin: "zǒulù", english: "To walk" },
{ chinese: "跑步", pinyin: "pǎobù", english: "To run" },
{ chinese: "工作", pinyin: "gōngzuò", english: "To work" },
{ chinese: "东西", pinyin: "dōngxi", english: "Thing" },
{ chinese: "手机", pinyin: "shǒujī", english: "Cellphone" },
{ chinese: "电脑", pinyin: "diànnǎo", english: "Computer" },
{ chinese: "书", pinyin: "shū", english: "Book" },
{ chinese: "衣服", pinyin: "yīfu", english: "Clothes" },
{ chinese: "鞋子", pinyin: "xiézi", english: "Shoes" },
{ chinese: "水", pinyin: "shuǐ", english: "Water" },
{ chinese: "食物", pinyin: "shíwù", english: "Food" },
{ chinese: "水果", pinyin: "shuǐguǒ", english: "Fruit" },
{ chinese: "颜色", pinyin: "yánsè", english: "Color" },
{ chinese: "好", pinyin: "hǎo", english: "Good" },
{ chinese: "不好", pinyin: "bù hǎo", english: "Not good / Bad" },
{ chinese: "大", pinyin: "dà", english: "Big" },
{ chinese: "小", pinyin: "xiǎo", english: "Small" },
{ chinese: "新", pinyin: "xīn", english: "New" },
{ chinese: "旧", pinyin: "jiù", english: "Old" },
{ chinese: "漂亮", pinyin: "piàoliang", english: "Beautiful / Pretty" },
{ chinese: "帅", pinyin: "shuài", english: "Handsome" },
{ chinese: "好吃", pinyin: "hǎochī", english: "Delicious" },
{ chinese: "好玩儿", pinyin: "hǎowánr", english: "Fun" }
];

const wordDisplay = document.getElementById("word-display");
const chineseWordElement = document.getElementById("chinese-word");
const pinyinElement = document.getElementById("pinyin");
const englishTranslationElement = document.getElementById("english-translation");
const randomizeButton = document.getElementById("randomize-button");

function getRandomWord() {
    const randomIndex = Math.floor(Math.random() * chineseWords.length);
    return chineseWords[randomIndex];
}

function displayWord(word) {
    chineseWordElement.textContent = word.chinese;
    pinyinElement.textContent = word.pinyin;
    englishTranslationElement.textContent = word.english;
}

randomizeButton.addEventListener("click", () => {
    const randomWord = getRandomWord();
    displayWord(randomWord);
});

// Display an initial word on page load
displayWord(getRandomWord());
